### ISSUE TITLE
Search - facets - tooltip texts

### ISSUE THREAD

**Issue by zozlak** [acdh-oeaw/arche-docker-config#17]
* open the [search page](https://arche-curation.acdh-dev.oeaw.ac.at/browser/discover?preferredLang=en&includeBinaries=0&linkNamedEntities=1&page=0&pageSize=10&facets%5Bhttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%5D=%5Bhttps%3A//vocabs.acdh.oeaw.ac.at/schema%23TopCollection%5D&noCache=0/?preferredLang=en&includeBinaries=0&linkNamedEntities=1&page=0&pageSize=10&facets%5Bhttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%5D=[https%3A%2F%2Fvocabs.acdh.oeaw.ac.at%2Fschema%23TopCollection]&noCache=0)
* provide texts to be displayed when you move a mouse cursor over the `?` buttons in the facets list
* you can check actual metadata properties used for a given facet on https://github.com/acdh-oeaw/arche-docker-config/blob/arche/yaml/smartSearch.yaml
* property descriptions can be found in what we call a [root table](https://arche.acdh.oeaw.ac.at/browser/api/getRootTable/en?_format=html)

**Comment by ramandell** [comment]
**Draft 1:**
**General tip about the facets? (maybe on the “Find resources” box above the facets?**
The combination of facets below is designed to help a user filter their search to discover data. As you begin your search the filters will actively begin to select the possible results Once a search is complete the user will need to “uncheck” boxes or reset filters.

**Temporal Coverage**
Beginning and end dates or period of time associated with the original material or data. 
Question: what values with this field accept? Just numerical? 

**Spatial coverage**
Location or area associated with the original material or data. This can be a present-day location or historic.

**Research Discipline**
Choose from the drop down below the field of study associated with the data you are interested in. Most datasets will be associated with multiple research disciplines. 

**Category**
	The kind of data you are searching for.

**License**
Choose one of the licenses below. Licenses are associated with each individual file, as well as with the entire collection of files. 

**Access restriction**
The type of restriction placed on data. Public access means there are no restrictions placed on data. Academic access provides access to all individuals affiliated with an academic institution. Restricted access refers to data that requires specific permission from the data owner.

**Type**
Choose one of the classes below. The TopCollection is the highest level containing the general metadata describing an entire collection. The collection contains metadata on a collection of files within a TopCollection. The resource contains metadata for a single digital object or file.

**Comment by zozlak** [comment]
Good for now. If we come up with something better, it's enough to update the https://github.com/acdh-oeaw/arche-docker-config/blob/arche/yaml/smartSearch.yaml
